# Generated by Django 5.1.5 on 2025-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to='api.stock'),
        ),
    ]
