# Generated by Django 5.1.5 on 2025-01-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_watchlist_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='WatchListEntry',
        ),
    ]
